using RayihaRestaurant.Core.Enums;

namespace RayihaRestaurant.Core.Extensions
{
    public static class PicturesEnumExtension
    {
    
        private static readonly Dictionary<Pictures, Bitmap> turMappings = new Dictionary<Pictures, Bitmap>
        {
            {Pictures.Close, Properties.Resources.ic_close },
            {Pictures.Dinner, Properties.Resources.ic_dinner_black },
            {Pictures.Logout, Properties.Resources.ic_logout },
            {Pictures.Logout_white, Properties.Resources.ic_logout_white },
            {Pictures.Minus, Properties.Resources.ic_minus },
            {Pictures.Password, Properties.Resources.ic_password },
            {Pictures.Plus, Properties.Resources.ic_plus },
            {Pictures.Table, Properties.Resources.ic_table },
            {Pictures.Table_white, Properties.Resources.ic_table_white },
            {Pictures.User, Properties.Resources.ic_user },
            {Pictures.Backgorund, Properties.Resources.ic_background },
            {Pictures.Restaurant_table, Properties.Resources.ic_restaurant_table },
            {Pictures.EzogelinCorbasi, Properties.Resources.ic_ezogelin_corbasi },
            {Pictures.MercimekCorbasi, Properties.Resources.ic_mercimek_corbasi },
            {Pictures.GununCorbasi, Properties.Resources.ic_gunun_corbasi },
            {Pictures.KasarliTost, Properties.Resources.ic_kasarli_tost },
            {Pictures.SucukluTost, Properties.Resources.ic_sucuklu_tost },
            {Pictures.KarisikTost, Properties.Resources.ic_karisik_tost },
            {Pictures.KavurmaliKasarliTost, Properties.Resources.ic_kavurmalı_kasarlı_tost },
            {Pictures.KlasikKavhvaltiTabagi, Properties.Resources.ic_klasik_kahvaltı_tabagi },
            {Pictures.RayihaSpecialKahvalti, Properties.Resources.ic_rayiha_special_kahvalti_tabagi },
            {Pictures.RayihaSerpmeKahvalti, Properties.Resources.ic_serpme_kahvalti },
            {Pictures.CobanSalata, Properties.Resources.ic_coban_salata },
            {Pictures.PilicSalata, Properties.Resources.ic_pilic_salata },
            {Pictures.TonBalikliSalata, Properties.Resources.ic_tonbalıklı_salata },
            {Pictures.MevsimSalata, Properties.Resources.ic_mevsim_salata },
            {Pictures.CitirSalata, Properties.Resources.ic_citir_salata },
            {Pictures.Hamburger, Properties.Resources.ic_hamburger },
            {Pictures.Cheesburger, Properties.Resources.ic_cheeseburger },
            {Pictures.TonBalikliSandwich, Properties.Resources.ic_ton_balıklı_sandwich },
            {Pictures.SigaraBoregi, Properties.Resources.ic_sigara_boregi },
            {Pictures.PacangaBoregi, Properties.Resources.ic_pacanga_boregi },
            {Pictures.ElmaDilimPatates, Properties.Resources.ic_elma_dilim_patates },
            {Pictures.PatatesKizartmasi, Properties.Resources.ic_patates_kizartmasi },
            {Pictures.IcliKofte, Properties.Resources.ic_icli_kofte },
            {Pictures.SoyaSosluTavuk, Properties.Resources.ic_soya_soslu_tavuk },
            {Pictures.MantarSosluTavuk, Properties.Resources.ic_mantar_soslu_tavuk },
            {Pictures.PilicSinitzel, Properties.Resources.ic_pilic_sinitzel },
            {Pictures.KoriSosluTavuk, Properties.Resources.ic_kori_soslu_tavuk },
            {Pictures.TavukSote, Properties.Resources.ic_tavuk_sote },
            {Pictures.UrfaKavurmasi, Properties.Resources.ic_urfa_kavurma },
            {Pictures.FirinSutlac, Properties.Resources.ic_fırın_sutlac },
            {Pictures.KabakTatlisi, Properties.Resources.ic_kabak_tatlisi },
            {Pictures.DondurmaTatli, Properties.Resources.ic_dondurma_tatlisi },
            {Pictures.Kunefe, Properties.Resources.ic_kunefe },
            {Pictures.AdanaKebap, Properties.Resources.ic_adana_kebap },
            {Pictures.UrfaKebap, Properties.Resources.ic_urfa_kebap },
            {Pictures.OzelIzgaraKofte, Properties.Resources.ic_ozel_izgara_kofte },
            {Pictures.KasarliKofte, Properties.Resources.ic_kasarli_kofte },
            {Pictures.KuzuSis, Properties.Resources.ic_kuzu_sis },
            {Pictures.TavukSis, Properties.Resources.ic_tavuk_sis },
            {Pictures.TavukKanat, Properties.Resources.ic_tavuk_kanat },
            {Pictures.TavukPirzola, Properties.Resources.ic_tavuk_pirzola1 },
            {Pictures.SucukIzgara, Properties.Resources.ic_sucuk_izgara },
            {Pictures.KarisikKebap, Properties.Resources.ic_karisik_kebap },
            {Pictures.RayihaSpecial, Properties.Resources.ic_rayiha_special },
            {Pictures.Antrikot, Properties.Resources.ic_antrikot },
            {Pictures.KuzuPirzola, Properties.Resources.ic_kuzu_pirzola },
            {Pictures.IskenderKebap, Properties.Resources.ic_iskender_kebap },
            {Pictures.CopSis, Properties.Resources.ic_cop_sis },
            {Pictures.KuzuCiger, Properties.Resources.ic_kuzu_ciger },
            {Pictures.Lahmacun, Properties.Resources.ic_lahmacun },
            {Pictures.OzelLahmacun, Properties.Resources.ic_ozel_lahmacun },
            {Pictures.AdanaDurum, Properties.Resources.ic_adana_durum },
            {Pictures.UrfaDurum, Properties.Resources.ic_urfa_durum },
            {Pictures.TavukSisDurum, Properties.Resources.ic_tavuk_sis_durum },
            {Pictures.CopSisDurum, Properties.Resources.ic_cop_sis_durum },
            {Pictures.KasarliPide, Properties.Resources.ic_kasarlı_pide },
            {Pictures.SucukluPide, Properties.Resources.ic_sucuklu_pide },
            {Pictures.KiymaliPide, Properties.Resources.ic_kiymali_pide },
            {Pictures.KusbasiliPide, Properties.Resources.ic_kusbasili_pide },
            {Pictures.KavurmaliPide, Properties.Resources.ic_kavurmali_pide },
            {Pictures.PastirmaliPide, Properties.Resources.ic_pastirmali_pide },
            {Pictures.KarisikPide, Properties.Resources.ic_karisik_pide },
            {Pictures.Cola, Properties.Resources.ic_cola },
            {Pictures.Fanta, Properties.Resources.ic_fanta },   
            {Pictures.Sprite, Properties.Resources.ic_sprite },
            {Pictures.Cappy, Properties.Resources.ic_cappy },
            {Pictures.Ayran, Properties.Resources.ic_ayran },
            {Pictures.MeyveliSoda, Properties.Resources.ic_meyveli_soda },
            {Pictures.Soda, Properties.Resources.ic_soda },
            {Pictures.Su, Properties.Resources.ic_su },
            {Pictures.Cay, Properties.Resources.ic_cay },
            {Pictures.FincanCay, Properties.Resources.ic_fincan_cay },
            {Pictures.MeyveCaylari, Properties.Resources.ic_meyve_caylari },
            {Pictures.TurkKahvesi, Properties.Resources.ic_turk_kahvesi },
            {Pictures.Nescafe, Properties.Resources.ic_nescafe },
            {Pictures.Salep, Properties.Resources.ic_salep },
            {Pictures.Cappuccino, Properties.Resources.ic_cappuccino },
            {Pictures.Espresso, Properties.Resources.ic_espresso },
            {Pictures.SicakCikolata, Properties.Resources.ic_sicak_cikolata },

        };

        public static Bitmap? PictureConverter(this int? value)
        {
            if (value == null) return null;
            Pictures pic = (Pictures)value;
            return turMappings.TryGetValue(pic, out Bitmap? picWithSpaces) ? picWithSpaces : null;
        }
    }
}

